export const SYSTEM_SET_MESSAGE = 'SYSTEM_SET_MESSAGE';
export const SYSTEM_CLEAR_MESSAGE = 'SYSTEM_CLEAR_MESSAGE';
export const SYSTEM_SET_THEME = 'SYSTEM_SET_THEME';
export const SYSTEM_SET_LOADING = 'SYSTEM_SET_LOADING';